Repository oxygen-updater/oxygen-updater, pull requests merged in 2019-08, with the labels that each got.

#34 Update strings.xml
  app/src/main/res/values-fr/strings.xml
Labels: translation

#35 Update french strings
  app/src/main/res/values-fr/strings.xml
Labels: translation

#44 Update fr/strings.xml
  app/src/main/res/values-fr/strings.xml
Labels: translation

#46 Added translations for Spanish
  app/src/main/res/values-es/strings.xml
Labels: translation

#49 Commit SettingsFragment synchronously to avoid crash during IAB setup
  app/src/main/java/com/arjanvlek/oxygenupdater/settings/SettingsActivity.java
Labels: bug

#47 Play Store account transfer (including AdMob, Firebase, etc.)
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/arjanvlek/oxygenupdater/news/NewsActivity.java
  app/src/main/java/com/arjanvlek/oxygenupdater/updateinformation/UpdateInformationFragment.java
  app/src/main/java/com/arjanvlek/oxygenupdater/views/AbstractFragment.java
  app/src/main/java/com/arjanvlek/oxygenupdater/views/MainActivity.java
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_update_information.xml
  app/src/main/res/layout/loading.xml
  app/src/main/res/values/strings.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: enhancement

#54 Updated Chinese Translation
  app/src/main/res/values-zh-rCN/strings.xml
Labels: translation

#57 Update fr/strings.xml
  app/src/main/res/values-fr/strings.xml
Labels: translation

#58 Chinese Translation Update
  app/src/main/res/values-zh-rCN/strings.xml
Labels: translation
